version: "3"
services:
    database:
        build:
            context: ./database
        environment:
            MYSQL_ROOT_PASSWORD: 'example'
            MYSQL_DATABASE: 'testDB'
            MYSQL_USER: 'testUser'
            MYSQL_PASSWORD: 'testUser'
        ports:
            - "3306:3306"
        volumes: 
            - ./database/data:/var/lib/mysql
    php-fpm:
        build:
            context: ./php-fpm
        volumes: 
            - ../src:/var/www
        depends_on:
            - database
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../src:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "127.0.0.1:8886:80"
        depends_on:
            - php-fpm
